export const INITIALIZE_APP = 'INITIALIZE_APP';

export const SET_USER = 'SET_USER';

export const SET_DRAWING_DESK = 'SET_DRAWING_DESK';
export const SET_DESK_OPTION = 'SET_DESK_OPTION';
export const SET_DESK_TOOL = 'SET_DESK_TOOL';
export const SET_DRAWING_DESK_CONTAINER_SIZE = 'SET_DRAWING_DESK_CONTAINER_SIZE';
export const SET_DRAWING_DESK_CANVAS_SIZE = 'SET_DRAWING_DESK_CANVAS_SIZE';
