export const INITIALIZE_APP = 'INITIALIZE_APP';

export const SET_USER = 'SET_USER';

export const SET_DRAWING_DESK = 'SET_DRAWING_DESK';
export const SET_DESK_OPTION = 'SET_DESK_OPTION';
export const SET_DESK_TOOL = 'SET_DESK_TOOL';
export const SET_DRAWING_DESK_CONTAINER_SIZE = 'SET_DRAWING_DESK_CONTAINER_SIZE';
export const SET_DRAWING_DESK_CANVAS_SIZE = 'SET_DRAWING_DESK_CANVAS_SIZE';

export const SET_SAVE_STATUS = 'SET_SAVE_STATUS';

export const LOAD_IMAGE_REQUEST = 'LOAD_IMAGE_REQUEST';
export const LOAD_IMAGE_SUCCESS = 'LOAD_IMAGE_SUCCESS';
export const LOAD_IMAGE_FAILURE = 'LOAD_IMAGE_FAILURE';

export const SAVE_IMAGE_REQUEST = 'SAVE_IMAGE_REQUEST';
export const SAVE_IMAGE_SUCCESS = 'SAVE_IMAGE_SUCCESS';
export const SAVE_IMAGE_FAILURE = 'SAVE_IMAGE_FAILURE';

export const DELETE_IMAGE_REQUEST = 'DELETE_IMAGE_REQUEST';
export const DELETE_IMAGE_SUCCESS = 'DELETE_IMAGE_SUCCESS';
export const DELETE_IMAGE_FAILURE = 'DELETE_IMAGE_FAILURE';
